/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ethInheritSol from "./eth_inherit.sol";
export type { ethInheritSol };
import type * as hazirlikSol from "./hazirlik.sol";
export type { hazirlikSol };
export type { HelloWorld } from "./HelloWorld";
export type { Token } from "./Token";
export * as factories from "./factories";
export type { Eth_Inherit } from "./eth_inherit.sol/Eth_Inherit";
export { Eth_Inherit__factory } from "./factories/eth_inherit.sol/Eth_Inherit__factory";
export type { Admin_and_Parent } from "./hazirlik.sol/Admin_and_Parent";
export { Admin_and_Parent__factory } from "./factories/hazirlik.sol/Admin_and_Parent__factory";
export { HelloWorld__factory } from "./factories/HelloWorld__factory";
export { Token__factory } from "./factories/Token__factory";
